# Generated by Django 4.2.1 on 2023-08-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(max_length=256, verbose_name="Отправитель"),
        ),
    ]
