# Generated by Django 4.2.1 on 2023-06-13 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homework",
            old_name="teacher_Student",
            new_name="teacher_student",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="teacher_Student",
            new_name="teacher_student",
        ),
    ]
