# Generated by Django 4.2.1 on 2023-09-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0014_alter_student_user_alter_teacher_user_and_more"),
        ("chats", "0002_alter_message_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="t_homeworks",
                to="clients.teacher",
                verbose_name="Учитель",
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="teacher_student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ts_homeworks",
                to="clients.teacherstudent",
                verbose_name="Псевдоученик",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="t_messages",
                to="clients.teacher",
                verbose_name="Учитель",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="teacher_student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ts_messages",
                to="clients.teacherstudent",
                verbose_name="Псевдоученик",
            ),
        ),
    ]
