# Generated by Django 4.1.6 on 2023-03-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="students",
            field=models.ManyToManyField(
                related_name="teachers",
                through="clients.TeacherStudent",
                to="clients.student",
                verbose_name="Студенты",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="teachers",
                to="clients.subject",
                verbose_name="Предметы",
            ),
        ),
        migrations.AlterField(
            model_name="teacherstudent",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teacherM2M",
                to="clients.student",
                verbose_name="Студент",
            ),
        ),
        migrations.AlterField(
            model_name="teacherstudent",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="studentM2M",
                to="clients.teacher",
                verbose_name="Учитель",
            ),
        ),
    ]
