# Generated by Django 4.1.6 on 2023-05-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0009_alter_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(null=True, upload_to="profiles/", verbose_name="Фотография"),
        ),
    ]
