# Generated by Django 4.2.1 on 2023-06-09 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0012_alter_teacherstudent_email_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacherstudent",
            options={
                "ordering": ("teacher",),
                "verbose_name": "Псевдоученик",
                "verbose_name_plural": "Псевдоученики",
            },
        ),
    ]
