# Generated by Django 4.2.1 on 2023-09-13 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0014_alter_student_user_alter_teacher_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        error_messages={"invalid": "Имя указанo некорректно"},
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(50),
                        ],
                        verbose_name="Имя",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={"invalid": "E-mail введен некорректно!"},
                        max_length=50,
                        validators=[
                            django.core.validators.EmailValidator(),
                            django.core.validators.MinLengthValidator(7),
                            django.core.validators.MaxLengthValidator(254),
                        ],
                        verbose_name="Электронная почта",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "waiting"), ("completed", "completed")],
                        default="waiting",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
