# Generated by Django 4.2.1 on 2023-11-02 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0015_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherstudent",
            name="phone",
            field=models.TextField(
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон введен некорректно. От 11 до 13 символов. Введите в формате: 89051234567",
                        regex="^((\\+7|7|8)[0-9]{10,12})$",
                    ),
                    django.core.validators.MinLengthValidator(11),
                    django.core.validators.MaxLengthValidator(13),
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
