version: "3.3"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
       - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: unless-stopped

  web:
    image: orbins/tutoroffice:latest
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: always
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.20
    volumes:
       - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_PORT: 5050
#      PGADMIN_CONFIG_SERVER_MODE: null
    ports:
      - "5050:80"
    restart: unless-stopped

  redis:
    image: redis:7-alpine3.17
    container_name: redis
    restart: always
    volumes:
      - redis:/data

  celery:
    image: orbins/tutoroffice:latest
    container_name: celery
    depends_on:
      - web
    restart:
      always
    command: celery -A core worker -l INFO

volumes:
  postgres:
  pgadmin:
  redis: