# Generated by Django 4.1.6 on 2023-03-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_teacher_students_alter_teacher_subjects_and_more"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="homework",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="lessons.homework",
                verbose_name="Домашняя работа",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher_student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="clients.teacherstudent",
                verbose_name="Учитель-Ученик",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="topic",
            field=models.TextField(
                blank=True, max_length=40, verbose_name="Тема урока"
            ),
        ),
    ]
