# Generated by Django 4.1.6 on 2023-03-28 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="homeworks",
                to="clients.teacher",
                verbose_name="Учитель",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="clients.teacher",
                verbose_name="Учитель",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher_student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="clients.teacherstudent",
                verbose_name="Учитель-Ученик",
            ),
        ),
    ]
