# Generated by Django 4.1.6 on 2023-03-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0002_alter_lesson_comment_alter_lesson_homework_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="homework",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="lessons.homework",
                verbose_name="Домашняя работа",
            ),
        ),
    ]
