# Generated by Django 4.1.6 on 2023-03-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='lessons.homework', verbose_name='Домашняя работа'),
        ),
    ]
