# Generated by Django 4.2.1 on 2023-06-02 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0010_alter_user_photo"),
        ("lessons", "0005_rename_comment_lesson_student_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="student_comment",
            field=models.TextField(
                blank=True, max_length=100, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="clients.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher_comment",
            field=models.TextField(
                blank=True, max_length=100, verbose_name="Комментарий"
            ),
        ),
    ]
