# Generated by Django 4.2.1 on 2023-09-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0014_alter_student_user_alter_teacher_user_and_more"),
        ("lessons", "0007_alter_lesson_student_comment_alter_lesson_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="t_lessons",
                to="clients.teacher",
                verbose_name="Учитель",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher_student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ts_lessons",
                to="clients.teacherstudent",
                verbose_name="Псевдоученик",
            ),
        ),
    ]
