# Generated by Django 4.1.6 on 2023-03-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="static/materials/", verbose_name="Файл материалов"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст материалов")),
                (
                    "type",
                    models.CharField(
                        choices=[("public", "public"), ("private", "private")],
                        default="private",
                        max_length=10,
                        verbose_name="Тип материалов",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clients.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="clients.teacher",
                        verbose_name="Учитель",
                    ),
                ),
                (
                    "teacher_student",
                    models.ManyToManyField(
                        related_name="materials", to="clients.teacherstudent"
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
                "ordering": ("subject", "teacher_id"),
            },
        ),
    ]
