# Generated by Django 4.1.6 on 2023-03-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_teacher_students_alter_teacher_subjects_and_more"),
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to="static/materials/",
                verbose_name="Файл материалов",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="teacher_student",
            field=models.ManyToManyField(
                related_name="materials",
                to="clients.teacherstudent",
                verbose_name="Учитель-Ученик",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="text",
            field=models.TextField(blank=True, verbose_name="Текст материалов"),
        ),
    ]
