# Generated by Django 4.1.6 on 2023-03-26 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0002_alter_material_file_alter_material_teacher_student_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ("subject", "teacher"),
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
            },
        ),
    ]
