# Generated by Django 4.1.6 on 2023-04-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0003_alter_material_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="text",
            field=models.TextField(blank=True, verbose_name="Текст к материалу"),
        ),
    ]
