# Generated by Django 4.1.6 on 2023-05-12 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0009_alter_user_photo"),
        ("materials", "0006_material_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="file",
            field=models.FileField(
                upload_to="backend_media/materials/%Y/%m/%d",
                verbose_name="Файл материалов",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="clients.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="teacher_student",
            field=models.ManyToManyField(
                null=True,
                related_name="materials",
                to="clients.teacherstudent",
                verbose_name="Учитель-Ученик",
            ),
        ),
    ]
