# Generated by Django 4.1.6 on 2023-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0009_alter_user_photo"),
        (
            "materials",
            "0007_alter_material_file_alter_material_subject_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="teacher_student",
            field=models.ManyToManyField(
                blank=True,
                related_name="materials",
                to="clients.teacherstudent",
                verbose_name="Учитель-Ученик",
            ),
        ),
    ]
