# Generated by Django 4.1.6 on 2023-05-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0008_alter_material_teacher_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="file",
            field=models.FileField(
                upload_to="materials/", verbose_name="Файл материалов"
            ),
        ),
    ]
