# Generated by Django 4.2.1 on 2023-06-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0009_alter_material_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="type",
            new_name="material_type",
        ),
        migrations.AddField(
            model_name="material",
            name="file_size",
            field=models.IntegerField(
                null=True, verbose_name="Размер файла (КБ)"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="file_type",
            field=models.CharField(
                max_length=25, null=True, verbose_name="Тип файла"
            ),
        ),
    ]
