name: Deploy to server

on:
  push:
    branches: ["release"]

jobs:

  build_and_push_to_docker_hub:
    name: Build docker images and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: action/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/tutoroffice:latest

  deploy:
    name: Deploy backend to the server
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Executing ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          port: ${{secrets.HOST_PORT}}
          username: ${{secrets.HOST_USER}}
          key: ${{secrets.HOST_SSH_KEY}}
          password: ${{secrets.HOST_PASSWORD}}
          script: |
            cd project
            sudo docker-compose -f docker-compose.prod.yaml stop
            sudo docker-compose -f docker-compose.prod.yaml rm -f web
            sudo docker-compose -f docker-compose.prod.yaml rm -f celery
            sudo docker-compose -f docker-compose.prod.yaml pull
            sudo docker-compose -f docker-compose.prod.yaml up -d
